defmodule PetalComponents.Collapsible do
  @moduledoc """
  One disclosure region: a trigger row that shows and hides the content under it.

      <.collapsible>
        <:trigger>Advanced options</:trigger>
        <p>Timeouts, retries and the webhook signing secret.</p>
      </.collapsible>

      <.collapsible open={@show_details} id="api-keys">
        <:trigger>API keys (3)</:trigger>
        <ul>...</ul>
      </.collapsible>

  ## Collapsible or accordion?

  This is one region with no neighbours: nothing closes when it opens, and there
  is no list of entries. When you have a set of sections where opening one should
  close the others, that is `PetalComponents.Accordion.accordion/1`.

  ## State

  Toggling is client-side `Phoenix.LiveView.JS`, so an open/close costs no round
  trip. The `open` attr sets the state the server renders, which means LiveView
  can drive it too: re-render with a changed assign and the region follows. Pass
  extra commands through `on_toggle` (analytics, a `phx-click` to persist the
  state) and they run before the component's own.

  ## Animation

  The height animation is the `grid-template-rows: 0fr -> 1fr` trick, so content
  of any height animates without measuring anything in JavaScript. Under
  `prefers-reduced-motion: reduce` the transition is dropped and the region snaps
  open, fully legible either way.

  ## Accessibility

  The trigger is a real `<button type="button">`, so Enter and Space work for
  free and focus stays put across toggles. It carries `aria-expanded` and
  `aria-controls` pointing at the content region, which is `role="region"`
  labelled by the trigger. While collapsed the content is `inert`, so it is out
  of the tab order and out of the accessibility tree instead of being an
  invisible trap. `disabled` uses the button's native disabled attribute.
  """
  use Phoenix.Component

  import PetalComponents.Helpers, only: [compose_js: 2, uniq_id: 1]
  import PetalComponents.Icon

  alias Phoenix.LiveView.JS

  attr :id, :string, default: nil, doc: "container id; autogenerated when omitted"
  attr :class, :any, default: nil, doc: "CSS class"
  attr :open, :boolean, default: false, doc: "render expanded; server-controlled open state"
  attr :disabled, :boolean, default: false, doc: "disables the trigger button"

  attr :on_toggle, JS,
    default: %JS{},
    doc: "additional JS commands composed onto the toggle, run before the component's own"

  attr :rest, :global

  slot :trigger, required: true, doc: "the always-visible row; rendered inside a button" do
    attr :class, :any
  end

  slot :inner_block, required: true, doc: "the collapsible content"

  @doc """
  A single disclosure region.

      <.collapsible open>
        <:trigger>What is included</:trigger>
        Everything in Pro, plus SSO.
      </.collapsible>
  """
  def collapsible(assigns) do
    # :id is a declared attr defaulting to nil, so assign_new never fires - test
    # the value, not the key.
    assigns = if assigns.id, do: assigns, else: assign(assigns, :id, uniq_id("collapsible"))

    ~H"""
    <div
      id={@id}
      class={["pc-collapsible", @class]}
      data-state={if @open, do: "open", else: "closed"}
      {@rest}
    >
      <button
        type="button"
        id={trigger_id(@id)}
        class={["pc-collapsible__trigger", trigger_class(@trigger)]}
        disabled={@disabled}
        aria-expanded={to_string(@open)}
        aria-controls={content_id(@id)}
        phx-click={toggle_collapsible(@id, @on_toggle)}
      >
        <span class="pc-collapsible__label">{render_slot(@trigger)}</span>
        <.icon
          name="hero-chevron-down-solid"
          class={["pc-collapsible__chevron", @open && "rotate-180"]}
        />
      </button>
      <div class="pc-collapsible__panel">
        <div
          id={content_id(@id)}
          class="pc-collapsible__content"
          role="region"
          aria-labelledby={trigger_id(@id)}
          inert={!@open}
        >
          <div class="pc-collapsible__body">{render_slot(@inner_block)}</div>
        </div>
      </div>
    </div>
    """
  end

  @doc """
  The JS command that toggles a collapsible by id.

  Exposed so a button elsewhere on the page can drive the same region:

      <.button phx-click={PetalComponents.Collapsible.toggle_collapsible("api-keys")}>
        Toggle
      </.button>
  """
  def toggle_collapsible(id, on_toggle \\ %JS{}) do
    compose_js(
      on_toggle,
      %JS{}
      # data-state on the container is what the CSS animates off, so the whole
      # open look (grid rows, any consumer overrides) flips from one attribute.
      |> JS.toggle_attribute({"data-state", "open", "closed"}, to: "##{id}")
      |> JS.toggle_attribute({"aria-expanded", "true", "false"}, to: "##{id}-trigger")
      |> JS.toggle_attribute({"inert", "true"}, to: "##{id}-content")
      |> JS.toggle_class("rotate-180", to: "##{id}-trigger .pc-collapsible__chevron")
    )
  end

  defp trigger_id(id), do: "#{id}-trigger"
  defp content_id(id), do: "#{id}-content"

  defp trigger_class([%{class: class} | _]), do: class
  defp trigger_class(_), do: nil
end
