defmodule PetalComponents.ContextMenu do
  use Phoenix.Component

  alias PetalComponents.Link

  @moduledoc """
  A right-click menu attached to a region of the page.

  Right-clicking anywhere inside the trigger region opens a floating menu at
  the cursor. Touch users get the same menu from a long press, and keyboard
  users open it with `Shift+F10` or the `Menu` key while focus is inside the
  region. Everything outside the region keeps the browser's own context menu.

  The panel is the same floating surface as `dropdown/1`, and the items share
  its anatomy - icons in the inner block, an optional `kbd` hint on the right,
  a `danger` variant for the destructive one.

  ## Examples

  The pointer path - right-click the card:

      <.context_menu id="file-card">
        <:trigger>
          <div class="p-6 border rounded-xl">Q3-forecast.xlsx</div>
        </:trigger>

        <.context_menu_item link_type="button" phx-click="open" label="Open" />
        <.context_menu_item link_type="button" phx-click="rename" label="Rename" />
        <.context_menu_separator />
        <.context_menu_item
          link_type="button"
          phx-click="delete"
          variant="danger"
          kbd="⌘⌫"
          label="Delete"
        />
      </.context_menu>

  Items take arbitrary content, so an icon is just an icon:

      <.context_menu id="doc-body">
        <:trigger>
          <p>Right-click this paragraph.</p>
        </:trigger>

        <.context_menu_label>Selection</.context_menu_label>
        <.context_menu_item link_type="button" phx-click="copy" kbd="⌘C">
          <.icon name="hero-clipboard" class="w-4 h-4" /> Copy
        </.context_menu_item>
        <.context_menu_item link_type="a" to="/search" label="Search the web" />
      </.context_menu>

  ## Touch and keyboard

  Long-pressing the region for half a second opens the menu at the finger,
  and the OS text-selection callout is suppressed inside the region so the
  press reads as a menu gesture rather than a selection.

  Keyboard users tab to the region (it is a focus stop) and press `Shift+F10`
  or the `Menu` key. The menu then opens at the region with the first item
  focused. Arrow keys move through the items and skip disabled ones, `Home`
  and `End` jump to the ends, `Enter` and `Space` activate, `Escape` closes
  and hands focus back to the region.

  ## Turning it off

  `disabled` drops the hook entirely, so right-clicking the region falls
  straight through to the browser's native menu:

      <.context_menu id="file-card" disabled={@read_only}>
        ...
      </.context_menu>
  """

  attr :id, :string, doc: "the component id; autogenerated if not set"

  attr :disabled, :boolean,
    default: false,
    doc:
      "disables the context menu entirely; right-click falls through to the browser default menu"

  attr :class, :any, default: nil, doc: "extra classes for the trigger region wrapper"
  attr :menu_class, :any, default: nil, doc: "extra classes for the menu panel"
  attr :rest, :global

  slot :trigger,
    required: true,
    doc:
      "the right-clickable region. Rendered as a block wrapper, so put anything inside - a card, a table row, a text area"

  slot :inner_block, required: true, doc: "the menu items"

  @doc """
  The trigger region and its menu. See the module docs for the pointer, touch
  and keyboard paths.

      <.context_menu id="file-card">
        <:trigger><div class="p-6 border rounded-xl">Q3-forecast.xlsx</div></:trigger>
        <.context_menu_item link_type="button" phx-click="open" label="Open" />
      </.context_menu>
  """
  def context_menu(assigns) do
    assigns =
      assigns
      |> assign_new(:id, fn -> "context_menu_#{Ecto.UUID.generate()}" end)
      |> then(&assign(&1, :menu_id, "#{&1.id}-menu"))

    ~H"""
    <div
      id={@id}
      class="pc-context-menu"
      phx-hook={if !@disabled, do: "PetalContextMenu"}
      data-pc-context-menu-panel={@menu_id}
      {@rest}
    >
      <%!-- Disabled drops the whole menu contract, not just the hook: a
            tab stop advertising aria-haspopup for a menu that will never
            show is a broken promise to a screen reader. --%>
      <div
        id={"#{@id}-trigger"}
        class={["pc-context-menu__trigger", @class]}
        tabindex={!@disabled && "0"}
        aria-haspopup={!@disabled && "menu"}
        aria-expanded={!@disabled && "false"}
        aria-controls={!@disabled && @menu_id}
      >
        {render_slot(@trigger)}
      </div>
      <%!-- popover=manual puts the panel in the top layer so an overflow-hidden
            ancestor (a card grid, a table cell, a scroll pane) can never clip
            it. Dismiss is ours rather than the UA's: light dismiss fires on
            pointerdown, which kills the menu the moment a touch drag starts. --%>
      <div
        id={@menu_id}
        popover="manual"
        role="menu"
        aria-orientation="vertical"
        tabindex="-1"
        class={["pc-context-menu__panel", @menu_class]}
      >
        {render_slot(@inner_block)}
      </div>
    </div>
    """
  end

  @doc """
  One command in a context menu.

      <.context_menu_item link_type="button" phx-click="rename" label="Rename" kbd="F2" />
  """
  attr :to, :string, default: nil, doc: "link path"
  attr :label, :string, default: nil, doc: "the item label; or pass content in the inner block"

  attr :link_type, :string,
    default: "button",
    values: ["a", "live_patch", "live_redirect", "button"],
    doc: "what the item renders as"

  attr :disabled, :boolean, default: false, doc: "greys the item out and takes it off the arrows"

  attr :variant, :string,
    default: "default",
    values: ["default", "danger"],
    doc: "danger renders the destructive treatment (danger ramp text, danger hover surface)"

  attr :kbd, :string, default: nil, doc: ~S|right-aligned keyboard shortcut hint, e.g. "⌘D"|
  attr :class, :any, default: nil, doc: "any additional CSS classes"
  attr :rest, :global, include: ~w(method download hreflang ping referrerpolicy rel target type)
  slot :inner_block, doc: "the item content - text, an icon, whatever the row needs"

  def context_menu_item(assigns) do
    ~H"""
    <Link.a
      link_type={@link_type}
      to={@to}
      class={[
        "pc-context-menu__item",
        @variant == "danger" && "pc-context-menu__item--danger",
        @disabled && "pc-context-menu__item--disabled",
        @class
      ]}
      disabled={@disabled}
      role="menuitem"
      tabindex="-1"
      aria-disabled={@disabled && "true"}
      data-pc-context-menu-item
      {@rest}
    >
      {render_slot(@inner_block) || @label}
      <kbd :if={@kbd} class="pc-context-menu__kbd" aria-hidden="true">{@kbd}</kbd>
    </Link.a>
    """
  end

  @doc """
  A non-interactive heading for a group of items.

      <.context_menu_label>Selection</.context_menu_label>
  """
  attr :class, :any, default: nil, doc: "any additional CSS classes"
  attr :rest, :global
  slot :inner_block, required: true, doc: "the heading text"

  def context_menu_label(assigns) do
    ~H"""
    <div class={["pc-context-menu__label", @class]} role="none" {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc """
  A thin divider between groups of items.
  """
  attr :class, :any, default: nil, doc: "any additional CSS classes"
  attr :rest, :global

  def context_menu_separator(assigns) do
    ~H"""
    <div class={["pc-context-menu__separator", @class]} role="separator" {@rest}></div>
    """
  end
end
