defmodule PetalComponents.Popover do
  use Phoenix.Component
  alias Phoenix.LiveView.JS
  import PetalComponents.Helpers, only: [compose_js: 2]

  @transition_in_base "transition transform ease-out duration-100"
  @transition_in_start "transform opacity-0 scale-95"
  @transition_in_end "transform opacity-100 scale-100"

  @transition_out_base "transition ease-in duration-75"
  @transition_out_start "transform opacity-100 scale-100"
  @transition_out_end "transform opacity-0 scale-95"

  @placements ~w(top top-start top-end bottom bottom-start bottom-end left left-start left-end right right-start right-end)

  @doc """
  A click-triggered panel anchored to its trigger. Opens on click, closes on
  click-away or Escape. CSS positioned - no JavaScript dependencies.

  ## Examples

      <.popover placement="bottom-start" trigger_class="pc-button pc-button--md pc-button--white">
        <:trigger>
          Open settings
        </:trigger>
        <.h5>Dimensions</.h5>
        <%!-- panel content: forms, menus, anything --%>
      </.popover>

  The trigger slot renders *inside* a `<button>` (native button semantics are
  required for the top-layer mode's `popovertarget`), so don't put another
  button in it - pass the trigger's content (text, an icon, an avatar) and
  style the button itself with `trigger_class`.

  ## Escaping clipped containers (top layer)

  A popover inside a container with `overflow: hidden` (a collapsed sidebar, a
  table cell, a modal) gets cut off by default, because the panel is positioned
  within that container. Pass `top_layer` to render the panel in the browser's
  top layer instead - it will overlay everything, unclipped:

      <.popover top_layer placement="right-start">
        <:trigger>
          <.avatar size="sm" name="Jane Doe" />
        </:trigger>
        <%!-- account switcher panel, etc. --%>
      </.popover>

  Top-layer mode uses the native HTML popover attribute (open/close and
  light-dismiss are handled by the browser) plus the `PetalPopover` hook for
  positioning, so it needs LiveView with the petal_components hooks registered.
  Without the hook the panel still opens, centered by the browser default.
  """

  attr :id, :string, doc: "the panel id; autogenerated if not set"

  attr :placement, :string,
    default: "bottom",
    values: @placements,
    doc: "which side of the trigger the panel appears on, with optional -start/-end alignment"

  attr :top_layer, :boolean,
    default: false,
    doc: "render the panel in the browser top layer so it escapes overflow-clipped containers"

  attr :class, :any, default: nil, doc: "extra classes for the wrapper"
  attr :trigger_class, :any, default: nil, doc: "extra classes for the trigger button"
  attr :panel_class, :any, default: nil, doc: "extra classes for the panel"

  attr :on_close, JS,
    default: %JS{},
    doc: "additional JS commands to run when the popover closes (default mode only)"

  attr :rest, :global

  slot :trigger, required: true, doc: "the trigger content, rendered inside a button"
  slot :inner_block, required: true, doc: "the panel content"

  def popover(assigns) do
    assigns = assign_new(assigns, :id, fn -> "popover_#{Ecto.UUID.generate()}" end)

    if assigns.top_layer do
      render_top_layer(assigns)
    else
      render_anchored(assigns)
    end
  end

  defp render_anchored(assigns) do
    trigger_id = "#{assigns.id}-trigger"

    hide_panel =
      JS.hide(
        to: "##{assigns.id}",
        transition: {@transition_out_base, @transition_out_start, @transition_out_end}
      )

    hide =
      compose_js(
        assigns.on_close,
        JS.set_attribute(hide_panel, {"aria-expanded", "false"}, to: "##{trigger_id}")
      )

    # Escape closes AND returns focus to the trigger; scoped to the component
    # (not the window) so a stray Escape elsewhere never steals focus.
    hide_and_refocus = JS.focus(hide, to: "##{trigger_id}")

    toggle =
      JS.toggle_attribute(
        JS.toggle(
          to: "##{assigns.id}",
          display: "block",
          in: {@transition_in_base, @transition_in_start, @transition_in_end},
          out: {@transition_out_base, @transition_out_start, @transition_out_end}
        ),
        {"aria-expanded", "true", "false"}
      )

    assigns =
      assign(assigns,
        hide: hide,
        hide_and_refocus: hide_and_refocus,
        toggle: toggle,
        trigger_id: trigger_id
      )

    ~H"""
    <div
      class={["pc-popover", @class]}
      phx-click-away={@hide}
      phx-keydown={@hide_and_refocus}
      phx-key="Escape"
      {@rest}
    >
      <button
        type="button"
        id={@trigger_id}
        class={["pc-popover__trigger", @trigger_class]}
        phx-click={@toggle}
        aria-haspopup="dialog"
        aria-expanded="false"
        aria-controls={@id}
      >
        {render_slot(@trigger)}
      </button>
      <div
        id={@id}
        role="dialog"
        style="display: none;"
        class={["pc-popover__panel", placement_class(@placement), @panel_class]}
      >
        {render_slot(@inner_block)}
      </div>
    </div>
    """
  end

  defp render_top_layer(assigns) do
    ~H"""
    <div class={["pc-popover", @class]} {@rest}>
      <button
        type="button"
        class={["pc-popover__trigger", @trigger_class]}
        popovertarget={@id}
        aria-haspopup="dialog"
        aria-controls={@id}
      >
        {render_slot(@trigger)}
      </button>
      <div
        id={@id}
        popover="auto"
        role="dialog"
        phx-hook="PetalPopover"
        data-placement={@placement}
        class={["pc-popover__panel pc-popover__panel--top-layer", @panel_class]}
      >
        {render_slot(@inner_block)}
      </div>
    </div>
    """
  end

  defp placement_class(placement), do: "pc-popover__panel--#{placement}"
end
