defmodule PetalComponents.Tooltip do
  use Phoenix.Component

  @doc """
  A pure-CSS tooltip that appears on hover or keyboard focus. No JavaScript required.

  ## Examples

      <.tooltip label="Add to library">
        <.button size="sm">Hover me</.button>
      </.tooltip>

      <.tooltip placement="right" label="Settings" />

  Rich content via the `:content` slot:

      <.tooltip placement="bottom">
        <:content>
          Saved <span class="font-semibold">2 minutes ago</span>
        </:content>
        <.icon name="hero-check-circle" class="w-5 h-5" />
      </.tooltip>

  ## Disabling at runtime

  Pass `disabled` to render the trigger without any tooltip. To toggle from the
  client (e.g. only show tooltips while a sidebar is collapsed), add or remove
  the `pc-tooltip--suppressed` class on the wrapper - `JS.add_class/2`,
  `JS.remove_class/2`, or any client-side binding works.

  ## Accessibility

  The bubble carries `role="tooltip"` and an `id` (autogenerated, or pass your
  own). For screen readers to announce it, reference that id from the focusable
  trigger element with `aria-describedby`:

      <.tooltip id="save-tip" label="Save (⌘S)">
        <.icon_button aria-describedby="save-tip">
          <.icon name="hero-check" />
        </.icon_button>
      </.tooltip>

  The tooltip already opens on keyboard focus (`focus-within`), so with the id
  wired it is fully keyboard and screen-reader accessible.
  """

  attr :id, :string, doc: "id for the tooltip bubble; autogenerated if not set"
  attr :label, :string, default: nil, doc: "the tooltip text (or use the :content slot)"

  attr :placement, :string,
    default: "top",
    values: ["top", "bottom", "left", "right"],
    doc: "which side of the trigger the tooltip appears on"

  attr :disabled, :boolean, default: false, doc: "when true, no tooltip is rendered"
  attr :arrow, :boolean, default: true, doc: "show the arrow pointing at the trigger"
  attr :class, :any, default: nil, doc: "extra classes for the wrapper"
  attr :content_class, :any, default: nil, doc: "extra classes for the tooltip bubble"
  attr :rest, :global

  slot :inner_block, required: true, doc: "the trigger content"
  slot :content, doc: "rich tooltip content; overrides the label attr"

  def tooltip(assigns) do
    assigns = assign_new(assigns, :id, fn -> "tooltip_#{Ecto.UUID.generate()}" end)

    ~H"""
    <span class={["pc-tooltip group/pc-tooltip", @class]} {@rest}>
      {render_slot(@inner_block)}
      <span
        :if={!@disabled && (@label not in [nil, ""] || @content != [])}
        id={@id}
        role="tooltip"
        class={["pc-tooltip__content", placement_class(@placement), @content_class]}
      >
        <%= if @content != [] do %>
          {render_slot(@content)}
        <% else %>
          {@label}
        <% end %>
        <span :if={@arrow} class={"pc-tooltip__arrow pc-tooltip__arrow--" <> @placement}></span>
      </span>
    </span>
    """
  end

  defp placement_class(placement), do: "pc-tooltip__content--#{placement}"
end
